### ISSUE TITLE
Request to push new version to npm

### ISSUE THREAD

**Issue by chadlwilson** [benmarch/spel2js#4]
Hi - very useful library, thanks!

If you are ready to do so - are you able to push a new version (`0.2.4` I guess) to NPM? There seems to be some packaging issue we have with the published `0.2.3` version that appears to be resolved on HEAD; possibly due to the switch to webpack; but that doesn't seem to be released yet.

**Comment by benmarch** [comment]
Hey @chadlwilson, thanks for the reminder, I will do that today!

**Comment by chadlwilson** [comment]
Great, looking forward to it!

**Comment by benmarch** [comment]
All set, 0.2.4 is available on NPM.

**Comment by chadlwilson** [comment]
Thanks, working out of the box for us on RN with Jest + RN's Metro bundler now :)

**Comment by chadlwilson** [comment]
Should the `bower.json` also be updated btw? Doesn't affect our usage, but thought I'd ask.

**Comment by benmarch** [comment]
Thanks for pointing that out! I just released 0.2.5 without `.babelrc` and fixed the release config to include `bower.json`.
