### ISSUE TITLE
`contains` method is not working.

### ISSUE THREAD

**Issue by Cicko** [benmarch/spel2js#7]
When I am trying to evaluate the following expression:
```js
{'PHONE','EMPLOYMENT_PHONE','WORK_PHONE'}.contains(classification)
```

Error is threw:
![image](https://user-images.githubusercontent.com/16807198/66563290-c7517100-eb5d-11e9-8140-dc1e89ed508c.png)

__It looks that the *contains* method is not supported__

Here I leave all data needed to reproduce it:

```javascript
import { SpelExpressionEvaluator } from 'spel2js';

const context = {
    classification: 'PHONE',
};
const expr = `{'PHONE','EMPLOYMENT_PHONE','WORK_PHONE'}.contains(classification)`;
const compiledPrecondition = SpelExpressionEvaluator.compile(expr);
const result = compiledPrecondition.eval(context);

```

**Comment by Cicko** [comment]
I guess is not working because __contains__ is an Array method part of the core library which doesn't work in Javascript. As workaround I solved it by transforming it into a __matches__ expression:
```
`classification matches '^PHONE$ | ^EMPLOYMENT_PHONE$ | ^WORK_PHONE$'`
```

**Comment by benmarch** [comment]
@Cicko, good catch, this should be a quick fix.
